stages:
  - build
  - test
  - dev
  - production

build_job:
  stage: build
  tags: 
    - dev
  script:
    - pwd
    - ls -la
    - echo 'Building'

test_app:
  stage: test
  tags: 
    - dev
  script:
    - cd search_engine_crawler
    - pip3 install -r requirements.txt -r requirements-test.txt
    - python3 -m unittest discover -s tests/ 
    - coverage run -m unittest discover -s tests/ 
    - coverage report --include crawler/crawler.py

test_ui:
  stage: test
  tags: 
    - dev
  script:
    - cd search_engine_ui
    - pip install -r requirements.txt -r requirements-test.txt
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include ui/ui.py
    
deploy_dev:
  stage: dev
  tags: 
    - dev
  script:
    - docker-compose up -d

deploy_prod:
  stage: production
  when: manual
  tags: 
    - prod
  script:
    - docker-compose up -d

