---
- name: Register runner to GitLab
  command: >
    gitlab-runner register
    --non-interactive
    --url '{{ gitlab_runner_coordinator_url }}'
    --registration-token '{{ gitlab_runner_registration_token }}'
    --description '{{ gitlab_runner.name|default(ansible_hostname+"-"+gitlab_runner_index|string) }}'
    --tag-list '{{ gitlab_runner.tags|default([]) | join(",") }}'
    {% if gitlab_runner.run_untagged|default(true) %}
    --run-untagged
    {% endif %}
    --executor '{{ gitlab_runner.executor|default("shell") }}'
    --limit '{{ gitlab_runner.concurrent_specific|default(0) }}'
    --locked='{{ gitlab_runner.locked|default(false) }}'
    {% for env_var in gitlab_runner.env_vars|default([]) %}
    --env '{{ env_var }}'
    {% endfor %}
    --docker-image '{{ gitlab_runner.docker_image|default("") }}'
    {% if gitlab_runner.docker_privileged|default(false) %}
    --docker-privileged
    {% endif %}
    {% for volume in gitlab_runner.docker_volumes | default([]) %}
    --docker-volumes "{{ volume }}"
    {% endfor %}
    --ssh-user '{{ gitlab_runner.ssh_user|default("") }}'
    --ssh-host '{{ gitlab_runner.ssh_host|default("") }}'
    --ssh-port '{{ gitlab_runner.ssh_port|default("") }}'
    --ssh-password '{{ gitlab_runner.ssh_password|default("") }}'
    --ssh-identity-file '{{ gitlab_runner.ssh_identity_file|default("") }}'
    {% if gitlab_runner.cache_type is defined %}
    --cache-type '{{ gitlab_runner.cache_type }}'
    --cache-shared '{{ gitlab_runner.cache_shared }}'
    {% if gitlab_runner.cache_path is defined %}
    --cache-path '{{ gitlab_runner.cache_path }}'
    {% endif %}
    {% if gitlab_runner.cache_s3_server_address is defined %}
    --cache-s3-server-address '{{ gitlab_runner.cache_s3_server_address }}'
    --cache-s3-access-key '{{ gitlab_runner.cache_s3_access_key }}'
    --cache-s3-secret-key '{{ gitlab_runner.cache_s3_secret_key }}'
    {% endif %}
    --cache-s3-bucket-name '{{ gitlab_runner.cache_s3_bucket_name }}'
    --cache-s3-bucket-location '{{ gitlab_runner.cache_s3_bucket_location }}'
    --cache-s3-insecure '{{ gitlab_runner.cache_s3_insecure }}'
    {% endif %}
    {% if gitlab_runner.extra_registration_option is defined %}
    {{ gitlab_runner.extra_registration_option }}
    {% endif %}
  when:
    - configured_runners.stderr.find('\n' + gitlab_runner.name|default(ansible_hostname+'-'+gitlab_runner_index|string)) == -1
    - gitlab_runner.state|default('present') == 'present'
  no_log: true
